version: '3.8'

services:
  jamvas-backend:
    container_name: jamvas-backend
    build:
      context: ./jamvas-backend
    ports:
      # Bind host port 8000 to container port 3000
      # Will be available at http://localhost:8000
      - "8000:3000"