apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamvas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: jamvas-frontend-container
          image: ghcr.io/ynnckth/jamvas-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-credentials
