apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamvas-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: jamvas-backend-container
          image: ghcr.io/ynnckth/jamvas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-credentials
