name: Backend CI/CD

on:
  push:
    branches:
      - "main"
    paths:
      - "jamvas-backend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "jamvas-backend/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write # permission to push images to Github Packages container registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set application version
        uses: falnyr/replace-env-vars-action@master
        env:
          BUILD_VERSION: 42.1
          COMMIT_HASH: nanoya
        with:
          filename: ./jamvas-backend/src/appVersion.ts

      # TODO: Image versioning instead of overriding latest
      - name: ⚒️ Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./jamvas-backend
          file: ./jamvas-backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - uses: azure/webapps-deploy@v2
        name: 🚀 Deploy to Azure App Service
        with:
          app-name: 'jamvas'
          images: ghcr.io/${{ github.repository }}:latest
