name: Build Backend

on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
    paths:
      - "jamvas-backend/**"
      - ".github/workflows/build-backend.yml"
      - ".github/workflows/release-backend.yml"
      - ".github/workflows/sonar-scan.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "jamvas-backend/**"
      - ".github/workflows/build-backend.yml"
      - ".github/workflows/release-backend.yml"
      - ".github/workflows/sonar-scan.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write # permission to push images to Github Packages container registry

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "⚙️ Install dependencies"
        run: |
          cd jamvas-backend
          npm ci

      - name: "🔬 Run tests with coverage"
        run: |
          cd jamvas-backend
          npm run test:cov

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - "test"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Determine and set build version and commit hash environment variables"
        run: |
          echo "BUILD_VERSION=${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: "Set application version information"
        uses: falnyr/replace-env-vars-action@master
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
          COMMIT_HASH: ${{ env.COMMIT_HASH }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        with:
          filename: ./jamvas-backend/src/appVersion.ts

      - name: "Login to GitHub Packages container registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Version the published docker images (currently always overriding latest)
      - name: "⚒️ Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          context: ./jamvas-backend
          file: ./jamvas-backend/Dockerfile
          push: true
          tags: ghcr.io/jamvas:latest
