name: Build Frontend

on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
    paths:
     - "jamvas-frontend/**"
     - ".github/workflows/build-frontend.yml"
     - ".github/workflows/release-frontend.yml"
     - ".github/workflows/sonar-scan.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "jamvas-frontend/**"
      - ".github/workflows/build-frontend.yml"
      - ".github/workflows/release-frontend.yml"
      - ".github/workflows/sonar-scan.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "⚙️ Install dependencies"
        run: |
          cd jamvas-frontend
          npm ci 

      - name: "🔬 Run tests"
        run: |
          cd jamvas-frontend
          npm run test:ci

  build:
    runs-on: ubuntu-latest
    needs:
      - "test"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Determine and set build version and commit hash environment variables"
        run: |
          echo "BUILD_VERSION=${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: "⚙️ Install dependencies"
        run: |
          cd jamvas-frontend
          npm ci

      - name: "⚒️ Build for demo environment"
        run: |
          cd jamvas-frontend
          VITE_BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }}
          VITE_BACKEND_API_BASE_URL=${{ vars.BACKEND_API_BASE_URL }}
          VITE_BUILD_VERSION=${{ env.BUILD_VERSION }} 
          VITE_COMMIT_HASH=${{ env.COMMIT_HASH }}
          VITE_BRANCH_NAME=${{ env.BRANCH_NAME }}
          npm run build
        env:
          VITE_BACKEND_BASE_URL: ${{ vars.BACKEND_BASE_URL }}
          VITE_BACKEND_API_BASE_URL: ${{ vars.BACKEND_API_BASE_URL }}
          VITE_BUILD_VERSION: ${{ env.BUILD_VERSION }}
          VITE_COMMIT_HASH: ${{ env.COMMIT_HASH }}
          VITE_BRANCH_NAME: ${{ env.BRANCH_NAME }}

      - name: "⬆️📦 Upload built artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "frontend-dist"
          path: "./jamvas-frontend/dist"
