name: Build Backend

on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "bugfix/**"
    paths:
      - "jamvas-backend/**"
      - ".github/workflows/build-backend.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "jamvas-backend/**"
      - ".github/workflows/build-backend.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write # permission to push images to Github Packages container registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine and set build version and commit hash environment variables
        run: |
          echo "BUILD_VERSION=${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Set application version
        uses: falnyr/replace-env-vars-action@master
        env:
          BUILD_VERSION: ${{ env.BUILD_VERSION }}
          COMMIT_HASH: ${{ env.COMMIT_HASH }}
        with:
          filename: ./jamvas-backend/src/appVersion.ts

      # TODO: Version the published docker images (currently always overriding latest)
      - name: ⚒️ Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./jamvas-backend
          file: ./jamvas-backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
