name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write # permission to push images to Github Packages container registry
  pages: write    # permission to deploy frontend to Github Pages

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Image versioning instead of overriding latest
      - name: ⚒️ Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./jamvas-backend
          file: ./jamvas-backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd jamvas-frontend
          npm ci

      - name: ⚒️ Build for demo environment
        run: |
          cd jamvas-frontend
          VITE_BACKEND_BASE_URL=${{variables.VITE_BACKEND_BASE_URL}}
          VITE_BACKEND_API_BASE_URL=${{variables.VITE_BACKEND_API_BASE_URL}}
          npm run build

      - name: Setup Github Pages
        uses: actions/configure-pages@v3

      - name: Upload built artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './jamvas-frontend/dist'

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

