name: CI/CD

on:
  push:
    branches: [ "main", "feature/github-actions-wf" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Image versioning instead of overriding latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./jamvas-backend
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
