name: Release Backend

on:
  # Trigger after the "Build Backend" workflow is completed on the main branch
  # Conclusion of build workflow completion is checked on job level
  workflow_run:
    workflows:
      - "Build Backend"
    branches:
      - "main"
    types:
      - "completed"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to GitHub Packages container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure via CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - uses: azure/webapps-deploy@v2
        name: 🚀 Deploy docker image to Azure App Service
        with:
          app-name: 'jamvas'
          images: ghcr.io/${{ github.repository }}:latest

  skip:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Skipping release due to failed build'
